# Generated by Django 5.2.3 on 2025-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionhistory",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="predictionhistory",
            name="bathrooms",
        ),
        migrations.RemoveField(
            model_name="predictionhistory",
            name="parking",
        ),
        migrations.RemoveField(
            model_name="predictionhistory",
            name="stories",
        ),
        migrations.AlterField(
            model_name="predictionhistory",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="predictionhistory",
            name="bedrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
