# Generated by Django 5.2.3 on 2025-07-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0002_rename_created_at_predictionhistory_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="airconditioning",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="basement",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="bathrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="furnishingstatus",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="guestroom",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="hotwaterheating",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="mainroad",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="parking",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="prefarea",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="stories",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
